version: "3.9"

services:
  <%= container_name %>:
    image: "singtao-registry.cn-hongkong.cr.aliyuncs.com/<%= namespace %>/<%= container_name %>:<%= version %>"
    restart: always
    ports:
      - "<%= port %>:8080"
    working_dir: /var/www/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
